name: 'Add Reviewed-by Trailer to Pull Request'
description: 'Adds a "Reviewed-by" trailer to the pull request description every time a user approves the changes.'
author: 'Ernesto Puerta'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'
runs:
  using: node20
  main: dist/index.js
inputs:
  states:
    description: 'Comma-separated list of pull request review states to consider for adding the "Reviewed-by" trailer.: approved, change_requested, commented'
    required: true
    default: 'approved'
